In [1]:
import numpy as np
import matplotlib.pyplot as plt

#import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import axes3d, Axes3D
plt.style.use('seaborn-whitegrid')
#%matplotlib inline
a = np.linspace(-1,5,1000)

X = np.array([
    [0,0, 1],
    [0,1, 1],
    [1, 0, 1],
    [1, 1, 1],

])

y = np.array([1,1,-1,-1])

def perceptron_sgd(X, Y):
    w = np.zeros(len(X[0]))
    eta = 1
    epochs = 20
    if (w[0]==w[1]==w[2]==0):
        plt.plot(a,0*a,linestyle='solid')
    for t in range(epochs):
        for i, x in enumerate(X):
            if (np.dot(X[i], w)*Y[i]) <= 0:
                w = w + eta*X[i]*Y[i]
                print(w)
                plt.plot([0,0], [0,1], 'r^')
                plt.plot([1,1], [0,1], 'g*')
                #plt.figure()
                
                fig = plt.figure()
                

                ax = plt.axes(projection='3d')
                ax = Axes3D(fig)
                plt.plot((w[1]/w[0])*a-(w[2]/w[0]),a,linestyle='dashed')
                

    return w

w = perceptron_sgd(X,y)
print(w)

plt.plot([0,0], [0,1], 'r^')
plt.plot([1,1], [0,1], 'g*')



[0. 0. 1.]
[-1.  0.  0.]
[-1.  0.  1.]


/srv/conda/lib/python3.6/site-packages/ipykernel_launcher.py:40: RuntimeWarning: invalid value encountered in double_scalars
/srv/conda/lib/python3.6/site-packages/ipykernel_launcher.py:40: RuntimeWarning: divide by zero encountered in double_scalars


[-2.  0.  0.]
[-2.  0.  1.]
[-2.  0.  1.]
